language: node_js
node_js:
  - '0.12'
  - '0.11'
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar"
  - "java -jar selenium-server-standalone-2.39.0.jar > /tmp/selenium.log 2> /tmp/selenium.error &"
script: "npm test && npm run test-browser"
install:
  - npm install
deploy:
  provider: heroku
  app: headless-decider
  api_key:
    secure: YWv+Rgxo7gC6pwLyFCLt+x/CpdQ02KIh+Y4JgkTMU/DozeteFADHWaIeWlT2sU/1z3+HRHdyTych0gliSmsctGQSGIxepxmJ285X5OoM5fYtxRCk+CZx/9PmjVKtG5s1jbUKDV/kdtbAZPv2GS00UlQO4jKI1bLelK3YcCoXrYM=
