language: node_js
node_js:
  - '0.12'
  - '0.11'
before_script:
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar
  - export DISPLAY=:99.0
  - xvfb-run java -jar selenium-server-standalone-2.31.0.jar > /dev/null &
  - sleep 5
script: "npm test && npm run test-browser"
install:
  - npm install
deploy:
  provider: heroku
  app: headless-decider
  api_key:
    secure: YWv+Rgxo7gC6pwLyFCLt+x/CpdQ02KIh+Y4JgkTMU/DozeteFADHWaIeWlT2sU/1z3+HRHdyTych0gliSmsctGQSGIxepxmJ285X5OoM5fYtxRCk+CZx/9PmjVKtG5s1jbUKDV/kdtbAZPv2GS00UlQO4jKI1bLelK3YcCoXrYM=
