language: node_js
node_js:
    - 'iojs-v2.0.1'
install:
    - npm install
script:
    - npm test
    - npm run test-zombie
deploy:
  provider: heroku
  app: headless-decider
  api_key:
    secure: YWv+Rgxo7gC6pwLyFCLt+x/CpdQ02KIh+Y4JgkTMU/DozeteFADHWaIeWlT2sU/1z3+HRHdyTych0gliSmsctGQSGIxepxmJ285X5OoM5fYtxRCk+CZx/9PmjVKtG5s1jbUKDV/kdtbAZPv2GS00UlQO4jKI1bLelK3YcCoXrYM=
